-- Inserts gerados a partir de professores.xls
-- siape = matricula conforme indicado
-- status 1 = ativo

INSERT INTO professores (id, nome, siape, email, status, createdAt, updatedAt) VALUES
(UUID(), 'Aecio da Silva Martins',                          '1228722',     'aecio.martins@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Alanny Silva Luz',                                '2271969',     'alanny.luz@ifma.edu.br',              1, NOW(), NOW()),
(UUID(), 'Ana Karoline de Olivera Goncalves',               '60630488398', 'karolinegoncalves41@gmail.com',       1, NOW(), NOW()),
(UUID(), 'Ananda Veloso Amorim Oliveira',                   '2174649',     'ananda.oliveira@ifma.edu.br',         1, NOW(), NOW()),
(UUID(), 'Ana Patricia de Andrade Ferreira',                '2326158',     'ana.ferreira@ifma.edu.br',            1, NOW(), NOW()),
(UUID(), 'Ana Rayonara de Sousa Albuquerque',               '1993705',     'rayonara.albuquerque@ifma.edu.br',    1, NOW(), NOW()),
(UUID(), 'Anderson Oliveira da Silva',                      '1963721',     'anderson.silva@ifma.edu.br',          1, NOW(), NOW()),
(UUID(), 'Andrea Lima Barros',                              '1964083',     'andrea.barros@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Andreia Mariana Araujo Machado',                  '1244814',     'andreia.machado@ifma.edu.br',         1, NOW(), NOW()),
(UUID(), 'Andre Wallas da Silva Sousa',                     '2342485',     'andre.wallas@ifma.edu.br',            1, NOW(), NOW()),
(UUID(), 'Annaya Assuncao Pereira Ribeiro',                 '1620844',     'annaya.assuncao@ifma.edu.br',         1, NOW(), NOW()),
(UUID(), 'Bruno Vicente Alves de Lima',                     '1226388',     'brunovicente.lima@ifma.edu.br',       1, NOW(), NOW()),
(UUID(), 'Clarissa Maria Brito Lima',                       '2339684',     'clarissa.lima@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Diego Roberto Rodrigues Orsano',                  '1836367',     'diego.rodrigues@ifma.edu.br',         1, NOW(), NOW()),
(UUID(), 'Diogo Vinicius de Sousa Silva',                   '1132172',     'diogo.silva@ifma.edu.br',             1, NOW(), NOW()),
(UUID(), 'Douglas dos Santos Silva',                        '2345177',     'douglas.silva@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Elcio Daniel Sousa Barros',                       '1860969',     'elcio.barros@ifma.edu.br',            1, NOW(), NOW()),
(UUID(), 'Erlan de Araujo Silva',                           '3149781',     'erlan.silva@ifma.edu.br',             1, NOW(), NOW()),
(UUID(), 'Francicleia Vieira Ribeiro de Oliveira',          '2571587',     'francicleia.ribeiro@ifma.edu.br',     1, NOW(), NOW()),
(UUID(), 'Francilio Benicio Santos de Moraes Trindade',     '1508992',     'fbenicio@ifma.edu.br',                1, NOW(), NOW()),
(UUID(), 'Francisca Marcia Costa de Souza',                 '1963983',     'francisca.souza@ifma.edu.br',         1, NOW(), NOW()),
(UUID(), 'Francisco Alan de Oliveira Santos',               '2331838',     'franciscoalan.santos@ifma.edu.br',    1, NOW(), NOW()),
(UUID(), 'Fredson Anderson Brito de Castro',                '2408251',     'fredson.castro@ifma.edu.br',          1, NOW(), NOW()),
(UUID(), 'Gabriela Oliveira Parentes da Costa',             '2312341',     'gabriela.parentes@ifma.edu.br',       1, NOW(), NOW()),
(UUID(), 'Gielson Vitor Oliveira Veras',                    '1258500',     'gielson.veras@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Glicia Lorainne Moreira Silva',                   '1006036',     'glicia.silva@ifma.edu.br',            1, NOW(), NOW()),
(UUID(), 'Hosana Maria da Silva Sousa',                     '2342286',     'hosana.sousa@ifma.edu.br',            1, NOW(), NOW()),
(UUID(), 'Iasmynne Elaine da Conceicao Borges Leal',        '3394152',     'iasmynne.leal@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Joana Celia Ferreira Moura',                      '2277896',     'joana.moura@ifma.edu.br',             1, NOW(), NOW()),
(UUID(), 'Joao Paulo Marques Silva',                        '2282550',     'joao.marques@ifma.edu.br',            1, NOW(), NOW()),
(UUID(), 'Johnathan Oliveira Silva',                        '3483531',     'johnathan.silva@ifma.edu.br',         1, NOW(), NOW()),
(UUID(), 'Jose de Arimatea de Sousa',                       '1828129',     'jose.arimatea@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Jose Jeovane Reges Cordeiro',                     '2331959',     'jose.cordeiro@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Josimar Hendrio Ferraz Borges',                   '1145981',     'josimar.borges@ifma.edu.br',          1, NOW(), NOW()),
(UUID(), 'Jussie Soares da Rocha',                          '1886837',     'jussie.rocha@ifma.edu.br',            1, NOW(), NOW()),
(UUID(), 'Katia Simone Parente Mazza Malta',                '46261397368', 'katia.malta@hotmail.com',             1, NOW(), NOW()),
(UUID(), 'Kelcius Rodrigues Ferreira',                      '1915383',     'kelcius.ferreira@ifma.edu.br',        1, NOW(), NOW()),
(UUID(), 'Marcelo Silva Cavalcante',                        '00230248365', 'marceloc.adm@gmail.com',              1, NOW(), NOW()),
(UUID(), 'Marcio dos Santos Rodrigues',                     '1048227',     'marcio.rodrigues@ifma.edu.br',        1, NOW(), NOW()),
(UUID(), 'Marcos Neves da Silva',                           '3459584',     'marcos.neves@ifma.edu.br',            1, NOW(), NOW()),
(UUID(), 'Marcos Vinicius Barros e Silva',                  '3515250',     'marcos.barros@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Mardoqueu Sousa Telvina',                         '3077773',     'mardoqueu.telvina@ifma.edu.br',       1, NOW(), NOW()),
(UUID(), 'Maria do Socorro Ribeiro da Silva',               '1903931',     'socorro.ribeiro@ifma.edu.br',         1, NOW(), NOW()),
(UUID(), 'Maria Irisnete Barbosa Lima',                     '3474217',     'maria.barbosa@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Marison Assuncao de Oliveira',                    '07749085300', 'marison.oliveira098@gmail.com',       1, NOW(), NOW()),
(UUID(), 'Micilane Nascimento dos Santos',                  '2174409',     'micilane.santos@ifma.edu.br',         1, NOW(), NOW()),
(UUID(), 'Nadia da Silva Borges Brito',                     '1835753',     'nadia.borges@ifma.edu.br',            1, NOW(), NOW()),
(UUID(), 'Pablo Silva Imperio',                             '1699038',     'pablo.imperio@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Rivania da Silva Lira',                           '2020069',     'rivania.lira@ifma.edu.br',            1, NOW(), NOW()),
(UUID(), 'Robert Charles Moreira Caland',                   '1921426',     'robertcaland@ifma.edu.br',            1, NOW(), NOW()),
(UUID(), 'Robert Silva Lima',                               '2311281',     'robert.lima@ifma.edu.br',             1, NOW(), NOW()),
(UUID(), 'Susana Kelly Gomes Oliveira',                     '1293499',     'susana.oliveira@ifma.edu.br',         1, NOW(), NOW()),
(UUID(), 'Thalita Vitoria Castelo Branco Nunes Silva',      '1837473',     'thalita.silva@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Vagner da Silva Araujo',                          '2329000',     'vagner.araujo@ifma.edu.br',           1, NOW(), NOW()),
(UUID(), 'Washington dos Santos Costa',                     '2393495',     'washington.costa@ifma.edu.br',        1, NOW(), NOW()),
(UUID(), 'Willams da Silva Lima',                           '1877101',     'willams.lima@ifma.edu.br',            1, NOW(), NOW());
